# Generated by Django 3.1 on 2020-08-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='', max_length=254)),
                ('image', models.ImageField(upload_to='media/images')),
                ('article', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
