# Generated by Django 3.1 on 2020-08-24 21:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='article',
            field=tinymce.models.HTMLField(),
        ),
    ]
