# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-05 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='leave',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
    ]
