# Generated by Django 3.1 on 2020-08-14 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200205_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='BusinessName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='leave',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pot',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='team',
        ),
        migrations.AddField(
            model_name='profile',
            name='joined',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
