# Generated by Django 3.1 on 2020-08-15 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200814_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='businessname',
            new_name='telephone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='joined',
        ),
    ]
