# Generated by Django 3.1 on 2021-02-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20200831_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='start_time',
            field=models.CharField(default='start time', max_length=10),
        ),
    ]
