# Generated by Django 3.1.3 on 2021-08-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_auto_20210323_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitors',
            name='user',
        ),
        migrations.AddField(
            model_name='visitors',
            name='email',
            field=models.EmailField(default='user@user.com', max_length=254),
        ),
        migrations.AddField(
            model_name='visitors',
            name='first_name',
            field=models.CharField(default='firstname', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitors',
            name='second_name',
            field=models.CharField(default='secondname', max_length=40),
            preserve_default=False,
        ),
    ]
