# Generated by Django 3.1.3 on 2021-08-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_auto_20210812_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='guests',
            name='business',
            field=models.CharField(default='business', max_length=254),
        ),
    ]
