# Generated by Django 3.1.3 on 2021-08-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0025_businessprofile_instagram'),
        ('meetings', '0008_auto_20210812_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitors',
            name='business',
        ),
        migrations.AddField(
            model_name='visitors',
            name='business',
            field=models.ManyToManyField(to='business.BusinessProfile'),
        ),
    ]
