# Generated by Django 3.1.3 on 2021-08-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0025_businessprofile_instagram'),
        ('meetings', '0009_auto_20210812_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guests',
            name='business',
        ),
        migrations.AddField(
            model_name='guests',
            name='business',
            field=models.ManyToManyField(to='business.BusinessProfile'),
        ),
        migrations.RemoveField(
            model_name='visitors',
            name='business',
        ),
        migrations.AddField(
            model_name='visitors',
            name='business',
            field=models.CharField(default='business', max_length=60),
            preserve_default=False,
        ),
    ]
