# Generated by Django 3.1.3 on 2021-08-13 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0025_businessprofile_instagram'),
        ('meetings', '0010_auto_20210812_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guests',
            name='business',
        ),
        migrations.AddField(
            model_name='guests',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.businessprofile'),
        ),
    ]
