# Generated by Django 3.1.3 on 2021-08-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0012_hosts'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='website',
            field=models.CharField(default='website', max_length=60),
            preserve_default=False,
        ),
    ]
