# Generated by Django 3.1.3 on 2021-09-27 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0014_meeting_presenter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='agenda_item1',
            new_name='Notes',
        ),
    ]
