# Generated by Django 3.1 on 2020-09-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200310_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
