# Generated by Django 3.1 on 2020-09-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200915_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Digital', 'Digital'), ('StartUp', 'StartUp')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
