# Generated by Django 3.1 on 2020-08-25 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_groups_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default=0, max_length=254)),
                ('e_mail', models.EmailField(max_length=150)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('business_type', models.CharField(choices=[('Graphic Design', 'Graphic Design'), ('Accountant', 'Accountant'), ('Solicitor', 'Solicitor')], max_length=254)),
                ('logo', models.ImageField(upload_to='media/images')),
                ('opening_hours', models.CharField(default=0, max_length=254)),
                ('number_emp', models.IntegerField()),
                ('location', models.CharField(default=0, max_length=254)),
                ('country', models.CharField(max_length=40)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('town_or_city', models.CharField(max_length=40)),
                ('street_address1', models.CharField(max_length=40)),
                ('street_address2', models.CharField(max_length=40)),
                ('county', models.CharField(max_length=40)),
                ('contact_name', models.CharField(default=0, max_length=254)),
                ('about', tinymce.models.HTMLField()),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, to='groups.groups')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
