# Generated by Django 3.1 on 2020-08-25 18:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='services',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
