# Generated by Django 3.1 on 2020-08-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_businessprofile_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='header_image',
            field=models.ImageField(default=1, upload_to='media/images'),
            preserve_default=False,
        ),
    ]
