# Generated by Django 3.1 on 2020-08-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_businessprofile_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='facebook',
            field=models.CharField(default=0, max_length=254),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='google',
            field=models.CharField(default=0, max_length=254),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='linkedin',
            field=models.CharField(default=0, max_length=254),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='twitter',
            field=models.CharField(default=0, max_length=254),
        ),
    ]
