# Generated by Django 3.1 on 2020-08-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20200826_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='legal_entity',
            field=models.CharField(choices=[('Sole trader', 'Sole trader'), ('Partnership', 'Partnership'), ('Limited Company', 'Limited Company')], default=1, max_length=254),
            preserve_default=False,
        ),
    ]
