# Generated by Django 3.1 on 2020-08-27 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_businessprofile_legal_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='group',
        ),
    ]
