# Generated by Django 3.1 on 2020-08-27 20:05

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_auto_20200827_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='about',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='e_mail',
            field=models.EmailField(default='name@somehwere.com', max_length=150),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='header_image',
            field=models.ImageField(blank=True, upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='logo',
            field=models.ImageField(blank=True, upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='services',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='street_address1',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
