# Generated by Django 3.1 on 2020-08-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_auto_20200827_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='business_type',
            field=models.CharField(choices=[('Graphic Design', 'Graphic Design'), ('Accountant', 'Accountant'), ('Solicitor', 'Solicitor'), ('Default', 'Default')], default='Default', max_length=254),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='legal_entity',
            field=models.CharField(choices=[('Sole trader', 'Sole trader'), ('Partnership', 'Partnership'), ('Limited Company', 'Limited Company')], default='Sole trader', max_length=254),
        ),
    ]
