# Generated by Django 3.1 on 2020-09-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_businessprofile_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='website',
            field=models.CharField(default='', max_length=254),
        ),
    ]
