# Generated by Django 3.1 on 2020-09-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_auto_20200924_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='logo',
            field=models.ImageField(default='media/images/member-3.png', upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='website',
            field=models.CharField(default='https://example.com', max_length=254),
        ),
    ]
