# Generated by Django 3.1 on 2020-09-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_auto_20200927_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='logo',
            field=models.ImageField(default='/images/black_tex.jpeg', upload_to='media/images'),
        ),
    ]
