# Generated by Django 3.1 on 2020-09-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_auto_20200927_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='logo',
            field=models.ImageField(blank=True, default='/images/dp/default.png', upload_to='media/images'),
        ),
    ]
