# Generated by Django 3.1 on 2020-09-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_auto_20200927_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='logo',
            field=models.ImageField(blank=True, default='images/default.png', upload_to='media/images'),
        ),
    ]
