# Generated by Django 3.1 on 2020-09-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_auto_20200927_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='logo',
            field=models.ImageField(blank=True, default='media/images/default_1.png', upload_to='media/images'),
        ),
    ]
