# Generated by Django 3.1 on 2020-10-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0022_auto_20200927_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='contact_name',
            field=models.CharField(default='My Name', max_length=254),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='e_mail',
            field=models.EmailField(default='name@somewhere.com', max_length=150),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='facebook',
            field=models.CharField(default='https://example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='google',
            field=models.CharField(default='https://example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='header_image',
            field=models.ImageField(blank=True, default='media/images/header_1.jpg', upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='linkedin',
            field=models.CharField(default='https://example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='twitter',
            field=models.CharField(default='https://example.com', max_length=254),
        ),
    ]
