# Generated by Django 3.1 on 2020-11-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0024_auto_20201106_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='instagram',
            field=models.CharField(default='https://example.com', max_length=254),
        ),
    ]
