# Generated by Django 3.1 on 2020-08-24 21:35

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(default=0, max_length=254)),
                ('groupLocation', models.CharField(default=0, max_length=254)),
                ('created', models.DateField(auto_now_add=True)),
                ('about', tinymce.models.HTMLField()),
            ],
        ),
    ]
